### ISSUE TITLE
Problem with main.py

### ISSUE THREAD

**Issue by Francesco1122** [jblanco89/Twitter-Telegram-Bot#1]
Good evening buddy, I have a little problem getting the script to run. I am getting this problem in main.py

line 24, in <module>
    tweet = listener.StreamListener(config.API_KEY, config.API_SECRET, config.TOKEN, config.TOKEN_SECRET)
TypeError: Stream.__init__() takes 3 positional arguments but 5 were given

**Comment by jblanco89** [comment]
Good evening buddy, thank you for letting me know about your issue. Could you kindly confirm if you have got `Authentication OK` output in your terminal after running `main.py`?

**Comment by Francesco1122** [comment]
Yes , after running `main.py` i have got the `Authentication OK`

**Comment by jblanco89** [comment]
Good, so authentication is OK then; it means your Twitter credentials are correct. Have you changed the file name from `config.example.py` to `config.py`? Have you ensured you're using `TOKEN` value from the Telegram bot accurately?

**Comment by Francesco1122** [comment]
1)yes, i have changed the file name
2)yes, the token is right (works in other scripts)
maybe the problem is the tweepy version?  (I have version 3.10.0)

**Comment by jblanco89** [comment]
Yes, it is!! I had forgotten to mention that before. From tweepy 4.0.0 and on, the streaming listener has changed. 
Please take a look at the changelog.
https://github.com/tweepy/tweepy/releases

**Comment by jblanco89** [comment]
Are you still dealing with the same issue mate?. Please let me know

**Comment by jblanco89** [comment]
Lack of response made me think issue was actually solved. Im going to close this thread.
